// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dzdyawzxvanwukwaknvj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImR6ZHlhd3p4dmFud3Vrd2FrbnZqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc3OTM2MTMsImV4cCI6MjA3MzM2OTYxM30.ZJklOuidDuMBwZQaWh_13NF5rsiCkYArNbSbF9DFrkE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});